from enum import Enum
class StrEnum(str, Enum):
    def __str__(self): return self.value
class MoneyManagementProfile(StrEnum):
    CAPITAL_PROTECTION_STANDARD="CAPITAL_PROTECTION_STANDARD"
class TradingMode(StrEnum):
    PAPER="PAPER"; LIVE="LIVE"
class RiskState(StrEnum):
    NORMAL="NORMAL"; CAUTION="CAUTION"; DEFENSIVE="DEFENSIVE"; LOCKED="LOCKED"; RECOVERY_25="RECOVERY_25"; RECOVERY_50="RECOVERY_50"
class DecisionResult(StrEnum):
    APPROVED="APPROVED"; SIZE_REDUCED="SIZE_REDUCED"; RISK_BLOCKED="RISK_BLOCKED"; INVALID_INPUT="INVALID_INPUT"; INSUFFICIENT_DATA="INSUFFICIENT_DATA"
class RiskBlockReason(StrEnum):
    NONE="NONE"; MAXIMUM_DRAWDOWN="MAXIMUM_DRAWDOWN"; DAILY_LOSS_LIMIT="DAILY_LOSS_LIMIT"; WEEKLY_LOSS_LIMIT="WEEKLY_LOSS_LIMIT"; MONTHLY_LOSS_LIMIT="MONTHLY_LOSS_LIMIT"; MAXIMUM_POSITION="MAXIMUM_POSITION"; TOTAL_EXPOSURE_LIMIT="TOTAL_EXPOSURE_LIMIT"; SYMBOL_EXPOSURE_LIMIT="SYMBOL_EXPOSURE_LIMIT"; MAXIMUM_LEVERAGE="MAXIMUM_LEVERAGE"; RISK_OF_RUIN_CRITICAL="RISK_OF_RUIN_CRITICAL"; CONSECUTIVE_LOSS_LIMIT="CONSECUTIVE_LOSS_LIMIT"; COOLDOWN_ACTIVE="COOLDOWN_ACTIVE"; RECOVERY_LIMIT="RECOVERY_LIMIT"; INVALID_EQUITY="INVALID_EQUITY"; INVALID_ENTRY_PRICE="INVALID_ENTRY_PRICE"; INVALID_STOP="INVALID_STOP"; INVALID_COST_ASSUMPTION="INVALID_COST_ASSUMPTION"; BELOW_MINIMUM_ORDER="BELOW_MINIMUM_ORDER"; INSUFFICIENT_DATA="INSUFFICIENT_DATA"; PROFIT_PROTECTION_LIMIT="PROFIT_PROTECTION_LIMIT"
class LimitSeverity(StrEnum):
    NONE="NONE"; SOFT="SOFT"; HARD="HARD"
class CooldownState(StrEnum):
    INACTIVE="INACTIVE"; ACTIVE="ACTIVE"
class RecoveryState(StrEnum):
    NOT_REQUIRED="NOT_REQUIRED"; IN_PROGRESS="IN_PROGRESS"; COMPLETED="COMPLETED"
