"""Stable, presentation-safe failure codes for the Supervisor boundary."""

from enum import Enum


class SupervisorFailureCode(str, Enum):
    INPUT_MISSING = "SUPERVISOR_INPUT_MISSING"
    INPUT_STALE = "SUPERVISOR_INPUT_STALE"
    INPUT_CONFLICTED = "SUPERVISOR_INPUT_CONFLICTED"
    INPUT_INVALID = "SUPERVISOR_INPUT_INVALID"
    TIMESTAMP_INVALID = "SUPERVISOR_TIMESTAMP_INVALID"
    SCHEMA_INVALID = "SUPERVISOR_SCHEMA_INVALID"
    EXTRA_FIELD_REJECTED = "SUPERVISOR_EXTRA_FIELD_REJECTED"
    UNKNOWN_AGENT = "SUPERVISOR_UNKNOWN_AGENT"
    CAPABILITY_DENIED = "SUPERVISOR_CAPABILITY_DENIED"
    DATA_SOURCE_DENIED = "SUPERVISOR_DATA_SOURCE_DENIED"
    ACTION_PROHIBITED = "SUPERVISOR_ACTION_PROHIBITED"
    MODE_NOT_ALLOWED = "SUPERVISOR_MODE_NOT_ALLOWED"
    MODE_PROMOTION_PROHIBITED = "SUPERVISOR_MODE_PROMOTION_PROHIBITED"
    PROVIDER_UNAVAILABLE = "SUPERVISOR_PROVIDER_UNAVAILABLE"
    PROVIDER_TIMEOUT = "SUPERVISOR_PROVIDER_TIMEOUT"
    OUTPUT_INVALID = "SUPERVISOR_OUTPUT_INVALID"
    FAIL_CLOSED = "SUPERVISOR_FAIL_CLOSED"
    STORE_UNAVAILABLE = "SUPERVISOR_STORE_UNAVAILABLE"
    STORE_FULL = "SUPERVISOR_STORE_FULL"
    EVENT_INVALID = "SUPERVISOR_EVENT_INVALID"
    DUPLICATE_EVENT = "SUPERVISOR_DUPLICATE_EVENT"
    READ_FAILED = "SUPERVISOR_READ_FAILED"
    CURSOR_INVALID = "SUPERVISOR_CURSOR_INVALID"
    EVENT_NOT_FOUND = "SUPERVISOR_EVENT_NOT_FOUND"
    REPLAY_UNAVAILABLE = "SUPERVISOR_REPLAY_UNAVAILABLE"
    OLLAMA_UNAVAILABLE = "SUPERVISOR_OLLAMA_UNAVAILABLE"
    MODEL_NOT_FOUND = "SUPERVISOR_MODEL_NOT_FOUND"
    CONNECTION_REFUSED = "SUPERVISOR_CONNECTION_REFUSED"
    OUTPUT_TOO_LARGE = "SUPERVISOR_OUTPUT_TOO_LARGE"
    SAFETY_REJECTED = "SUPERVISOR_SAFETY_REJECTED"


class SupervisorBoundaryError(ValueError):
    """An expected fail-closed rejection with a stable external code."""

    def __init__(self, code: SupervisorFailureCode, message: str) -> None:
        self.code = code
        super().__init__(message)
