# =========================
# EVENT TYPES (GLOBAL STANDARD)
# =========================

AI_DECISION = "AI_DECISION"
RISK_EVENT = "RISK_EVENT"
EXECUTION_EVENT = "EXECUTION_EVENT"
SYSTEM_EVENT = "SYSTEM_EVENT"

SIGNAL = "SIGNAL"
RISK = "RISK"
EXECUTION = "EXECUTION"
HEARTBEAT = "HEARTBEAT"
ALERT = "ALERT"